### ISSUE TITLE
Doesn't seem to work on my end

### ISSUE THREAD

**Issue by seiferflo** [FluffierThanThou/StackMerger#7]
Hi, I'm unable to get this mod to work. 
Changing priorities doesn't do anything and I don't see the option "tidy up" when right clicking on a resource. 
Could there be a mod conflict? Attached is RCC file.
Thanks for your help.
[RCC.txt](https://github.com/FluffierThanThou/StackMerger/files/984578/RCC.txt)

**Comment by FluffierThanThou** [comment]
Thanks for reporting! Please provide an output_log so I can figure out what exactly is going on. You can normally find the output log in the following location;
`C:\Program Files\Steam\steamapps\common\RimWorld\RimWorldWin_Data\output_log.txt`

If you changed the steam install location, alter the path accordingly.

**Comment by seiferflo** [comment]
Hi @FluffierThanThou Sorry for the late reply, I just saw your message.
Please find attached the requested file. many thanks.
[output_log.txt](https://github.com/FluffierThanThou/StackMerger/files/1014230/output_log.txt)

**Comment by FluffierThanThou** [comment]
StackMerger doesn't appear to be installed/active. You sure you got it enabled?

**Comment by seiferflo** [comment]
Yes 4th position ! Tried different positions, doesn't change anything

**Comment by FluffierThanThou** [comment]
I'll have a look. You're sure you can't manually make them merge stacks either? Try spawning some partial stacks in a stockpile with devtools and rightclicking some of them.

**Comment by seiferflo** [comment]
Did that, doesn't work. I did exactly like on the video on youtube but I don't have the right click option appearing

**Comment by FluffierThanThou** [comment]
I just realised that output_log is from an A16 playthrough. Are you sure you uploaded the correct output_log, and if you're still on A16, that you're using an A16 version of the mod?

**Comment by seiferflo** [comment]
targetVersion 0.16.1393 in about.xml 
Rimworld 0.16.1393 rev533 in version.txt

**Comment by FluffierThanThou** [comment]
right. This puts me in a bit of a dilemma, as my updates are normally pretty linear. I don't usually keep branches for older alphas around, and I can't very well make a fixed A16 release the latest version...

**Comment by seiferflo** [comment]
Ok, so what do you suggest? Should I update Stacker Merger? Will it still be compatible with Rimworld A16?

**Comment by FluffierThanThou** [comment]
No, it probably won't work with A16 (although you could give it a shot, it's not a complicated mod - back up your save first just in case). 

You are on the latest A16 release? I'm afraid I'm not going to be trying to fix the A16 releases, because I don't have any clues where the problem might lie, I would need to downgrade my RW install, modify my build scripts (or do it manually) and keep an extra branch on steam. 

I'm sorry, but all in all I have better things to do with my time, still have several mods that need updating and a number of bugs on the shelves...

**Comment by seiferflo** [comment]
No problem, thanks anyway. Good luck!
