### ISSUE TITLE
Performance drop if a colonist/animal merges something

### ISSUE THREAD

**Issue by kahranna** [FluffierThanThou/StackMerger#9]
My fps drop from 55-60 to 20-30 when I zoom in on a stockpile, especially if a colonist/animal will soon merge a stack. It also slows down the game in general and causes a lag if a raid/traider notification pops up. Deactivating the mod doesn't help.
[output_log.txt](https://github.com/FluffierThanThou/StackMerger/files/1240396/output_log.txt)

**Comment by FluffierThanThou** [comment]
"Deactivating the mod doesn't help". 

What makes you think it's caused by stack merger if the problem is also there *without* stack merger?

**Comment by kahranna** [comment]
Savegame without Stack Merger: no problem.
But once Stack Merger has been active, the savegame shows that problem, even if the mod is deactivated.

**Comment by FluffierThanThou** [comment]
ok... That's very odd, and I can't see anything in the output link that indicates any problems at all. 

If you're able and willing, I'd appreciate a few more output_logs, taken immediately after the issue occurred.
